--- #YAML:1.0
name:               Algorithm-Numerical-Shuffle
version:            2009110301
abstract:           Shuffle a list.
author:
    - Abigail <cpan@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    strict:               0
    Test::More:           0
    warnings:             0
requires:
    Exporter:  0
    perl:      5.006
    strict:    0
    warnings:  0
resources:
    repository:  git://github.com/Abigail/regexp--charclasses.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - algorithm
    - shuffle
    - shuffling
